Link to the HTML spec's "has focus steps".
w3c/clipboard-apis pull request #143
Opened 2021-05-20 11:49 UTC by mfalken

This clarifies what "currently focused" means.

2021-05-20 11:51 UTC, mfalken commented
@domenic @garykac can you review this? More context at https://github.com/jeremyroman/alternate-loading-modes/issues/55

2021-05-20 15:40 UTC, domenic requested changes

2021-05-20 15:40 UTC, domenic commented on index.bs
> +		is executing in the context of a document that [=has focus steps|has focus=].
Documents don't have focus. Specific elements inside them, or focusable areas, have focus.

Is this supposed to be about the browsing context having system focus?

2021-05-20 22:13 UTC, domenic approved these changes
LGTM, although ideally this would be in the actual algorithms instead of a magic patch at a distance from the privacy section of the spec. (That's a preexisting problem though, and not really in scope for you to fix...)

2021-05-20 22:14 UTC, mfalken commented
Thanks. I believe the original intent of the text is about system focus.  I'm not sure about one thing. Document.hasFocus() exists and uses https://html.spec.whatwg.org/multipage/interaction.html#has-focus-steps which looked convenient as it checks for system focus in the first step. I'm not sure if the other steps are needed. I just changed it to use system focus directly. Do you know what is going on here?

2021-05-20 22:40 UTC, domenic commented
The other steps handle iframe nesting cases. If you call `document.hasFocus()` inside an iframe, then this is true if:

- The iframe itself has focus within its parent (times N if it's multiply nested)
- The top-level BC has system focus

In non-iframe cases, target's BC = target's BC's TLBC, so candidate = target so the loop quits immediately.

2021-05-20 22:56 UTC, mfalken commented
I see. I wonder if the Clipboard spec also wants to disallow the API in iframes that don't have focus. In that case, would returning to "has focus steps" be better?

2021-05-21 20:12 UTC, domenic commented
Yes, that's a good point. Although you could make an argument for either behavior, probably the clipboard API spec authors intended the `document.hasFocus()` behavior.

I apologize for not reading your original PR closer. I think I assumed "has focus steps" was a link to https://html.spec.whatwg.org/#focused, but it's document-specific. So we should probably revert to your original.

2021-05-21 22:56 UTC, mfalken commented
No worries, I returned to "has focus steps" then. @garykac does this look good to you?

2021-05-24 15:51 UTC, mfalken commented
> No worries, I returned to "has focus steps" then. @garykac does this look good to you?

Sorry somehow I didn't realize @domenic has write access. I was assuming only the editors do. If you think it's OK I'm happy if you merge it. For the build error, I also have sent https://github.com/w3c/clipboard-apis/pull/147.

2021-05-24 16:03 UTC, domenic commented
Oh weird, I have write access, strange... I'd love it if we could get an editor to sign off before I touch anything though :).

2021-05-25 00:20 UTC, garykac approved these changes

2021-05-25 00:21 UTC, garykac commented
Adding links like this is great because it will make the (eventual) conversion to a more algorithmic spec easier. Thanks!

2021-05-25 01:22 UTC, merged